---
title: "Problems"

---

### Relaxation time in atomic fluids

Spherical colloidal particles of radius 30 nm and density $1.35 \mathrm{~g} \mathrm{~cm}^{-3}$ are suspended in water (temperature $25^{\circ} \mathrm{C}$, density $1.0 \mathrm{~g} \mathrm{~cm}^{-3}$, viscosity $1.0 \times 10^{-3}$ Pa s ). Calculate the average distance from the origin along a given axis travelled by a particle in 1 minute due to Brownian motion and sedimentation, respectively. What are the displacements after 1 hour?

### Equipartition

The equipartitioning theorem states that in thermal equilibrium each generalised co-ordinate which occurs in the total system energy only as a quadratic term contributes $(1 / 2) \mathrm{k}_{\mathrm{B}} \mathrm{T}$ to the mean energy of the system. Use the theorem to estimate the typical time it rakes atoms (or small molecules) in an atomic liquid to move distances of the order of their own size, i.e. estimate the relaxation time.

### Gravitational length

(a) Find the typical length scale ('gravitational length') of the distribution of polystyrene particles (density $\rho_{\mathrm{p}}=1.05 \times 10^{3} \mathrm{~kg} \mathrm{~m}^{-3}$ ) of radius 50 nm and $1 \mu \mathrm{~m}$ respectively, suspended in water (density $\rho_{\mathrm{w}}=1.00 \times 10^{3} \mathrm{~kg} \mathrm{~m}^{-3}$, viscosity $1.0 \times 10^{-3} \mathrm{~Pa} \mathrm{~s}$ ) at room temperature. Hint: The gravitational length is the height at which the concentration falls to $1 / \mathrm{e}$ of its greatest value.
(b) If a container of height $\mathrm{H}=4 \mathrm{~cm}$ contains a dilute suspension of these particles at an average concentration of $n_{a}$ particles per unit volume, what are the actual concentrations (in terms of $n_{a}$ ) at the top and bottom of the sample when sedimentation equilibrium has been reached.
(c) If the above sample is shaken up to give an initially uniform concentration and then left undisturbed, estimate how long it will take the concentration profile to reach its equilibrium state (A surprisingly long time!)

### Peclet number

A definition of a colloid is a particle small enough that its Brownian motion is not dominated by gravity. Thus if the particle is raised a distance equal to its radius, the increase in its gravitational potential energy must be less than the thermal energy $(3 / 2) \mathrm{k}_{\mathrm{B}} T$. Another measure of the relative importance of the effects of Brownian motion and gravity, is the Peclet number $\mathrm{Pe}=\tau_{R} / \tau_{\text {sed }}$. Here $\tau_{\mathrm{R}}$ is the time taken by a particle to diffuse a distance equal to its radius, and $\tau_{\text {sed }}$ is the time taken by it to sediment the same distance. When $\mathrm{Pe} \ll 1$, Brownian motion dominates; when $\mathrm{Pe} \gg 1$, gravity dominates. Show that the
condition $\mathrm{Pe}<1$ is more or less equivalent to the definition of a colloid given above.

### Diffusion equation

Prove by direct substitution that $n(x, t)=C(4 \pi D t)^{-1 / 2} \exp \left(-x^{2} / 4 D t\right)$ is indeed a solution to the 1 D diffusion equation $\partial n / \partial t=D^{\partial^{2} n} / \partial x^{2}$.
Discuss the meaning of the constant C .

### Mean square displacement

Starting from the diffusion equation, deduce the mean square displacement, $\left\langle x^{2}\right\rangle=2 D t$, without using the full solution to the diffusion equation.
Note that $n(x, t)$ is the number density, from which the probability density of finding a particle in the region $[\mathrm{x}, \mathrm{x}+\mathrm{dx}]$ during the time interval $[\mathrm{t}, \mathrm{t}+\mathrm{dt}]$, can be obtained by normalising with $\int n(x, t) d x=N$ (the total number of particles). Having this in mind, the mean square displacement is
$\left\langle x^{2}(t)\right\rangle=\frac{\int_{-\infty}^{\infty} x^{2} n(x, t) d x}{\int_{-\infty}^{\infty} n(x, t) d x}=\frac{1}{N} \int_{-\infty}^{\infty} x^{2} n(x, t) d x$
Hint: Multiply both sides of the 1D diffusion equation by $x^{2}$ and integrate by parts over $x$ to get an o.d.e for $\left\langle x^{2}\right\rangle$ with t as the independent variable.

### Relaxation time in colloidal suspensions

Use $\left\langle\underline{r}^{2}\right\rangle=6 D t$ and the Stokes-Einstein relation to show that the time $\tau_{\mathrm{R}}$ for a particle to diffuse its own radius $R$, scales as $R^{3}$. The relaxation time $\tau_{R}$ is a good estimate for the time taken to return to equilibrium after a disturbance. Estimate $\tau_{\mathrm{R}}$ for a suspension of spheres of radius $\mathrm{R} \approx 1 \mu \mathrm{~m}$, i.e. at the upper limit of the colloidal size range.

### Colloidal crystals

Colloidal crystals are observed for volume fractions $\phi$ between 0.545 and 0.74 . Show that the upper limit of $\phi=0.74$ corresponds to the closest packing in a fcc crystal. What is the average distance between the colloidal particles for the lower limit $\phi=0.545$ ? Hint: to get the average consider a simple cubic lattice of the same volume fraction

### Lagrange's expression for the radius of gyration

For N equal point masses at positions $\left\{\underline{R}_{j}\right\}$, the radius of gyration is defined by $R_{g}^{2}=\frac{1}{N} \sum_{j=1}^{N}\left(\underline{R}_{j}-\underline{R}_{G}\right)^{2}$ where $\underline{R}_{G}=\frac{1}{N} \sum_{j=1}^{N} \underline{R}_{j}$ is the position of the centre of mass. Show that

$$
R_{g}^{2}=\frac{1}{2 N^{2}} \sum_{j=1}^{N} \sum_{k=1}^{N}\left(\underline{R}_{j}-\underline{R}_{k}\right)^{2}
$$

Hint: Note that $\frac{1}{N} \sum_{j=1}^{N} 1=1$

### Mean length

Calculate the mean end-to end length of a freely jointed polymer consisting of $10^{5}$ monomers of length $4.322 \AA$. How does the end-to-end length change if the valence angle of the chain is fixed at $108^{\circ}$ ?

### Real data

Light scattering measurements on dilute solutions of polystyrene, of different molar masses M , at the theta temperature give the following results for the mean square radius of gyration $\left\langle R_{g}^{2}\right\rangle$ :

| $\mathrm{M}\left(10^{6} \mathrm{~g} \mathrm{~mol}^{-1}\right)$ | 4.04 | 1.56 | 1.20 | 1.06 | 0.626 | 0.394 |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| $<R_{g}^{2}>\left(\mathrm{nm}^{2}\right)$ | 3260 | 1210 | 928 | 770 | 484 | 305 |

(a) Show that these results are consistent with $\left\langle R_{g}^{2}\right\rangle^{1 / 2}=B M^{1 / 2} \quad\left(M=N M_{M}\right.$ where $N$ is the number of monomers in the chain and $M_{M}$ is the molar mass of one monomer; $M_{M}=100 \mathrm{~g} \mathrm{~mol}^{-1}$ ) and estimate the value of $B$.
(b) Given that the 'size' of a styrene monomer is about $\mathrm{b}_{0}=0.23 \mathrm{~nm}$, calculate the factor $C$ which represents the effect of restricted bond angles in $\left\langle R^{2}\right\rangle=C N b_{0}^{2}$. From $C$, calculate the bond angle $\theta$ which would apply if polystyrene can be represented by a freely-rotating chain. [Remember $\left.\left\langle R_{g}^{2}\right\rangle=\frac{1}{6}<R^{2}\right\rangle$ ]
(c) Calculate $\left.<R_{g}^{2}\right\rangle^{1 / 2}$ for a polystyrene chain of molar mass $1 \times 10^{7} \mathrm{~g} \mathrm{~mol}^{-1}$ at the theta temperature.
(d) For the chain of (c), estimate the fraction of the volume $\left.(4 \pi / 3)<R_{g}^{2}\right\rangle^{3 / 2}$ which is actually occupied by styrene monomers (assume that the density of
styrene when polymerised is about $1 \mathrm{~g} \mathrm{~cm}^{-3}$ ). What is the overlap concentration $c^{*}$ (in mass per volume)? How do you expect $c^{*}$ to change upon an increase (decrease) in temperature?

### Micelles

The volume of a linear hydrocarbon chain with $n$ carbon atoms is given by $v=(27.4+26.9 n) \times 10^{-3} \mathrm{~nm}^{3}$, and its critical chain length is $l_{c}=(0.154+0.1265 n)$ $n m$. An amphiphile has an anionic head group with an optimum head group area in aqueous solution of $a_{0}=0.65 \mathrm{~nm}^{2}$.
(i) What shape micelles are formed by amphiphiles with linear hydrocarbon chains having $\mathrm{n}=10$ ?
(ii) What is the average size and aggregation number of each micelle?

### Viscosity

For polystyrene, the variation of viscosity with temperature follows the Vogel-Fulcher law $B=710$ and $T_{0}=50^{\circ} \mathrm{C}$. Plot the function $\eta / \eta_{0}$ in the temperature range $80-150^{\circ} \mathrm{C}$. By what factor does the viscosity and relaxation time vary between the temperatures of $100-140^{\circ} \mathrm{C}$ ?

### The glass transition

For polystyrene, a relaxation time associated with configurational rearrangements, $\tau_{\text {config, }}$, follows a Vogel-Fulcher law,

$$
\tau_{\text {confg }}=\tau_{0} \exp \left(\frac{B}{T-T_{0}}\right)
$$

Where $\tau_{0}, \mathrm{~B}=710$ and $T_{0}=50^{\circ} \mathrm{C}$ are constants. A value of the experimental glass transition temperature is measured with an experiment carried out at an effective timescale $\tau_{\text {exp }}=1000$ s and found to be $101.4^{\circ} \mathrm{C}$.
(a) Another experiment is carried out at an effective timescale of $10^{5} \mathrm{~s}$. What is the value of the glass transition temperature obtained from this experiment?
(b) On what timescale must an experiment be carried out if it is to measure a glass transition temperature within $10^{\circ} \mathrm{C}$ of the Vogel-Fulcher temperature $T_{0}$. Is this practically possible?
