---
title: "Readings"

---

The best overall text is: R.A.L Jones, Soft Condensed Matter, Oxford University Press. Shelfmark [539.2 Jon].

Additionally, the following more specialised texts should also be useful. They can be found in the University Library under the stated shelfmark.

### Colloids

(1) D.F.Evans, H.Wennerström: The Colloidal Domain - Where Physics, Chemistry, Biology, and Technology Meet. VCH Publishers (1994). [541.18 Eva]
(2) R.J.Hunter: Introduction to Modern Colloid Science. Oxford University Press (1993). 541.18 Hun]
(3) W.B.Russel, D.A.Saville, W.R.Schowalter: Colloidal Dispersions Cambridge University Press (1989).[541.18 Rus]
(4) D.H.Everett: Basic Principles of Colloid Science.

Royal Society of Chemistry Paperbacks (1988) [ 541.18 Eve]

### Polymers and surfactants

(1) R.J. Young and P.A. Lovell: Introduction to polymers [678 You].
(2) M. Doi: Introduction to polymer physics [541.64 Doi]
(3) J.Israelachvili, Intermolecular and Surface Forces, Academic Press (1992), Chs. 16 and 17

### Glasses

(1) J. Zarzycki; Glasses and the vitreous state. Cambridge University Press (1991).
